### ISSUE TITLE
OI

### ISSUE THREAD

**Issue by Joshaby** [luscafter/botflood#1]
me da seu popoti

**Comment by luscafter** [comment]
EU NÃO ACREDITO FDP
KAKAKKAKAKAKAKKSHDHAHUADJHZHZBZHAHSHZHSBZBSHHAIQIAJSJQKQKWKAKKKAKKAKAKAKKAKAKAKAKAJHQHQUWUQISKNSBSBSGZHSHWHSJKKKKKKKKKKAJHAHAUAIOAOOOOOOKAJJAJAJAJAJHA

Em sáb, 9 de jan de 2021 às 22:35, José Henrique <notifications@github.com>
escreveu:
